
slurm_version: "26.05.2"

slurm_build_dir: /usr/local/src/slurm 
slurm_install_prefix: /usr/local 



slurm_configure_opts:
  - "--prefix={{ slurm_install_prefix }}"
  - "--with-munge"
  - "--with-pam_dir=/lib/x86_64-linux-gnu/security"
  - "--enable-pam"
  - "--sysconfdir=/etc/slurm"


