site_name: Cluster Ansible Build 
repo_url: https://github.com/JanErikHuehne/cluster_management 
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
nav:
  - Home: index.md
  - Roles:
    - munge: roles/munge.md
    - ldap_client: roles/ldap_client.md
  - Architecture: architecture.md
  - Host Vars: host_vars/index.md
  - Templates:
      - Overview: templ/index.md
      - slurm.conf.j2: templ/slurm_conf_j2.md
      - sssd.conf.j2:  templ/sssd_conf_j2.md
      - krb5.conf.j2:  templ/krb5_conf_j2.md