- name: Install Apache PAM auth module
  ansible.builtin.apt:
    name: libapache2-mod-authnz-pam
    state: present


- name: Enable authnz_pam Apache module
  ansible.builtin.command: a2enmod authnz_pam
  args:
    creates: /etc/apache2/mods-enabled/authnz_pam.load
  notify: restart apache2

- name: Install PAM service file for OnDemand
  ansible.builtin.copy:
    dest: /etc/pam.d/ood
    content: |
      @include common-auth
      @include common-account
    mode: "0644"
  notify: restart apache2